version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
